ren "D:\Projetos\MMSJ300\diptrace\DipTrace_Schematic_-_MMSJ300B_CPU_MEM_PERIF_V2_Page1.pdf" "DipTrace_Schematic_MMSJ300B_CPU_MEM_PERIF_V2_Page1.pdf"
ren "D:\Projetos\MMSJ300\diptrace\DipTrace_Schematic_-_MMSJ300B_CPU_MEM_PERIF_V2_Page2.pdf" "DipTrace_Schematic_MMSJ300B_CPU_MEM_PERIF_V2_Page2.pdf"
ren "D:\Projetos\MMSJ300\diptrace\DipTrace_Schematic_-_MMSJ300B_CPU_MEM_PERIF_V2_Page3.pdf" "DipTrace_Schematic_MMSJ300B_CPU_MEM_PERIF_V2_Page3.pdf"
ren "D:\Projetos\MMSJ300\diptrace\DipTrace_Schematic_-_MMSJ300B_PERIF_V2_Page1.pdf" "DipTrace_Schematic_MMSJ300B_PERIF_V2_Page1.pdf"
ren "D:\Projetos\MMSJ300\diptrace\DipTrace_Schematic_-_MMSJ300B_PERIF_V2_Page2.pdf" "DipTrace_Schematic_MMSJ300B_PERIF_V2_Page2.pdf"
